    var emeatproduct=function () {
        this.innerid= {
        value: null,
        iskey: true,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'innerid',
        info: '编号',
        remark: ''
        };
        this.menuid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'menuid',
        info: '菜单编号',
        remark: ''
        };
        this.keyword= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'keyword',
        info: '关键字',
        remark: ''
        };
        this.proname= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'proname',
        info: '商品名称',
        remark: ''
        };
        this.protype= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'protype',
        info: '商品类别',
        remark: ''
        };
        this.propic= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'propic',
        info: '商品图片',
        remark: ''
        };
        this.summary= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'summary',
        info: '商品摘要',
        remark: ''
        };
        this.introduction= {
        value: null,
        iskey: false,
        dbtype: 'text',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'introduction',
        info: '商品介绍',
        remark: ''
        };
        this.versioninfo= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'versioninfo',
        info: '规格型号',
        remark: ''
        };
        this.price= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'price',
        info: '价格信息',
        remark: ''
        };
        this.hits= {
        value: null,
        iskey: false,
        dbtype: 'int',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'hits',
        info: '查看次数',
        remark: ''
        };
        this.ordernum= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'ordernum',
        info: '排序（置顶用，空的默认最后）',
        remark: ''
        };
        this.tags= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'tags',
        info: '标签',
        remark: ''
        };
        this.remark= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'remark',
        info: '备注详情',
        remark: ''
        };
        this.statuscode= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'statuscode',
        info: '状态',
        remark: ''
        };
        this.createdtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createdtime',
        info: '创建时间',
        remark: ''
        };
        this.createrid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createrid',
        info: '创建人',
        remark: ''
        };
        this.modifiedtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifiedtime',
        info: '修改时间',
        remark: ''
        };
        this.modifierid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifierid',
        info: '修改人',
        remark: ''
        };
};
module.exports = emeatproduct;
