    var emeatorder=function () {
        this.innerid= {
        value: null,
        iskey: true,
        dbtype: 'char',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'innerid',
        info: '编号',
        remark: ''
        };
        this.orderid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'orderid',
        info: '订单ID',
        remark: ''
        };
        this.shopid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'shopid',
        info: '店铺ID',
        remark: ''
        };
        this.productid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'productid',
        info: '商品ID',
        remark: ''
        };
        this.quantity= {
        value: null,
        iskey: false,
        dbtype: 'smallint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'quantity',
        info: '购买数量',
        remark: ''
        };
        this.returnquantity= {
        value: null,
        iskey: false,
        dbtype: 'smallint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'returnquantity',
        info: '退货数量',
        remark: ''
        };
        this.costprice= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'costprice',
        info: '成本价',
        remark: ''
        };
        this.saleprice= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'saleprice',
        info: '销售价',
        remark: ''
        };
        this.discountamount= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'discountamount',
        info: '优惠金额',
        remark: ''
        };
        this.realtotalprice= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'realtotalprice',
        info: '实际应付金额',
        remark: ''
        };
        this.refundprice= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'refundprice',
        info: '退款价格',
        remark: ''
        };
        this.productname= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'productname',
        info: '商品名称',
        remark: ''
        };
        this.tags= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'tags',
        info: '商品标签（id列表）',
        remark: ''
        };
        this.tagsobj= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'tagsobj',
        info: '商品标签（json形式）',
        remark: ''
        };
        this.version= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'version',
        info: 'SKU版本',
        remark: ''
        };
        this.thumbnailsurl= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'thumbnailsurl',
        info: '缩略图',
        remark: ''
        };
        this.commisrate= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'commisrate',
        info: '分佣比例',
        remark: ''
        };
        this.enabledrefundamount= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'enabledrefundamount',
        info: '可退金额',
        remark: ''
        };
        this.enabledrefundintegral= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'enabledrefundintegral',
        info: '可退积分抵扣金额',
        remark: ''
        };
        this.coupondiscount= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'coupondiscount',
        info: '优惠券抵扣金额',
        remark: ''
        };
        this.statuscode= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'statuscode',
        info: '状态',
        remark: ''
        };
        this.createdtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createdtime',
        info: '创建时间',
        remark: ''
        };
        this.createrid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createrid',
        info: '创建人',
        remark: ''
        };
        this.modifiedtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifiedtime',
        info: '修改时间',
        remark: ''
        };
        this.modifierid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifierid',
        info: '修改人',
        remark: ''
        };
};
module.exports = emeatorder;
