    var emuser=function () {
        this.innerid= {
        value: null,
        iskey: true,
        dbtype: 'char',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'innerid',
        info: '编号',
        remark: ''
        };
        this.userid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'userid',
        info: '用户名',
        remark: ''
        };
        this.password= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'password',
        info: '密码',
        remark: ''
        };
        this.sex= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'sex',
        info: '性别',
        remark: ''
        };
        this.username= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'username',
        info: '姓名',
        remark: ''
        };
        this.nickname= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'nickname',
        info: '昵称',
        remark: ''
        };
        this.email= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'email',
        info: '邮箱',
        remark: ''
        };
        this.headportait= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'headportait',
        info: '头像地址',
        remark: ''
        };
        this.cardid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'cardid',
        info: '身份证号',
        remark: ''
        };
        this.phone= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'phone',
        info: '手机号',
        remark: ''
        };
        this.roleid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'roleid',
        info: '角色编号',
        remark: ''
        };
        this.deptid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'deptid',
        info: '部门编号',
        remark: ''
        };
        this.unitid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'unitid',
        info: '单位编号',
        remark: ''
        };
        this.statuscode= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'statuscode',
        info: '状态（0：申请，1：正常，2：停用）',
        remark: ''
        };
        this.createdtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createdtime',
        info: '创建时间',
        remark: ''
        };
        this.createrid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createrid',
        info: '创建人',
        remark: ''
        };
        this.modifiedtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifiedtime',
        info: '修改时间',
        remark: ''
        };
        this.modifierid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifierid',
        info: '修改人',
        remark: ''
        };
};
module.exports = emuser;
