    var emwechatfans=function () {
        this.innerid= {
        value: null,
        iskey: true,
        dbtype: 'char',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'innerid',
        info: '编号',
        remark: ''
        };
        this.wechatid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: false,
        name: 'wechatid',
        info: '公众号原始id',
        remark: ''
        };
        this.userid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'userid',
        info: '用户编号',
        remark: ''
        };
        this.msgtype= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'msgtype',
        info: '消息类型',
        remark: ''
        };
        this.socialid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'socialid',
        info: '渠道编号',
        remark: ''
        };
        this.nickname= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'nickname',
        info: '昵称',
        remark: ''
        };
        this.remarkname= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'remarkname',
        info: '备注名称',
        remark: ''
        };
        this.country= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'country',
        info: '国家',
        remark: ''
        };
        this.province= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'province',
        info: '省份',
        remark: ''
        };
        this.city= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'city',
        info: '城市',
        remark: ''
        };
        this.notes= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'notes',
        info: '备注',
        remark: ''
        };
        this.sex= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'sex',
        info: '性别',
        remark: ''
        };
        this.headportait= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'headportait',
        info: '头像地址',
        remark: ''
        };
        this.enddate= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'enddate',
        info: '结束时间',
        remark: ''
        };
        this.oraginalid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'oraginalid',
        info: '设备编号',
        remark: ''
        };
        this.param= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'param',
        info: '扩展内容',
        remark: ''
        };
        this.longitude= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'longitude',
        info: '经度（Y）',
        remark: ''
        };
        this.latitude= {
        value: null,
        iskey: false,
        dbtype: 'decimal',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'latitude',
        info: '纬度（X）',
        remark: ''
        };
        this.ptime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'ptime',
        info: '位置更新时间',
        remark: ''
        };
        this.usertype= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'usertype',
        info: '用户类型（0：粉丝，1：会员）',
        remark: ''
        };
        this.statuscode= {
        value: null,
        iskey: false,
        dbtype: 'tinyint',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'statuscode',
        info: '状态',
        remark: ''
        };
        this.createdtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createdtime',
        info: '创建时间',
        remark: ''
        };
        this.createrid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'createrid',
        info: '创建人',
        remark: ''
        };
        this.modifiedtime= {
        value: null,
        iskey: false,
        dbtype: 'datetime',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifiedtime',
        info: '修改时间',
        remark: ''
        };
        this.modifierid= {
        value: null,
        iskey: false,
        dbtype: 'varchar',
        oldvalue: null,
        isreset: false,
        isupdate: false,
        isreadonly: false,
        isnull: true,
        name: 'modifierid',
        info: '修改人',
        remark: ''
        };
};
module.exports = emwechatfans;
